# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KyvernoJson < Formula
  desc "Kyverno for any JSON-compatible payload."
  homepage "https://kyverno.github.io/kyverno-json"
  version "0.0.3-alpha.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kyverno/kyverno-json/releases/download/v0.0.3-alpha.1/kyverno-json_darwin_arm64.tar.gz"
      sha256 "f3e78164182bf01cf4f8b395210a64ce1c2033be3177c05625abb18aed0b3af1"

      def install
        bin.install "kyverno-json"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyverno/kyverno-json/releases/download/v0.0.3-alpha.1/kyverno-json_darwin_amd64.tar.gz"
      sha256 "a992c4b292c0b8a36c264a9e781628b3f24c78493170ad6f8d791f2c781e8e21"

      def install
        bin.install "kyverno-json"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyverno/kyverno-json/releases/download/v0.0.3-alpha.1/kyverno-json_linux_arm64.tar.gz"
      sha256 "a62c0f0c4acdf51359761283005c440ead8ff015a7b37f54bf98dd74827e91d9"

      def install
        bin.install "kyverno-json"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyverno/kyverno-json/releases/download/v0.0.3-alpha.1/kyverno-json_linux_amd64.tar.gz"
      sha256 "fced17e8a6ad0447b96adecbed5be2653e9f6b59bca3821fe243cba27a793606"

      def install
        bin.install "kyverno-json"
      end
    end
  end
end
