# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KyvernoJson < Formula
  desc "Kyverno for any JSON-compatible payload."
  homepage "https://kyverno.github.io/kyverno-json"
  version "0.0.2-alpha.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kyverno/kyverno-json/releases/download/v0.0.2-alpha.1/kyverno-json_darwin_arm64.tar.gz"
      sha256 "a81ea5390f072f204fd1b66349a6675897c6ca5883ecc2bcb5e002be1c89f892"

      def install
        bin.install "kyverno-json"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyverno/kyverno-json/releases/download/v0.0.2-alpha.1/kyverno-json_darwin_amd64.tar.gz"
      sha256 "7f5ef8c78eb2f5792780985b80afceeabf2a14b9e831f6cec856c905c207ee38"

      def install
        bin.install "kyverno-json"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyverno/kyverno-json/releases/download/v0.0.2-alpha.1/kyverno-json_linux_arm64.tar.gz"
      sha256 "a7f94c1d382c64cff61605342fa49360b09df52d4a2e6594005d0bdea94931d5"

      def install
        bin.install "kyverno-json"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kyverno/kyverno-json/releases/download/v0.0.2-alpha.1/kyverno-json_linux_amd64.tar.gz"
      sha256 "2713957a091501ad0dd48ef2fbd5ad7fa573867581cf85529a376af1ac70f65a"

      def install
        bin.install "kyverno-json"
      end
    end
  end
end
