# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KyvernoJson < Formula
  desc "Kyverno for any JSON-compatible payload."
  homepage "https://kyverno.github.io/kyverno-json"
  version "0.0.3-beta.1"

  on_macos do
    on_intel do
      url "https://github.com/kyverno/kyverno-json/releases/download/v0.0.3-beta.1/kyverno-json_darwin_amd64.tar.gz"
      sha256 "aa7e68de634c640bbc64e9fec52ca4f1baf86ec9184ccc71fbdde22c7f22551e"

      def install
        bin.install "kyverno-json"
      end
    end
    on_arm do
      url "https://github.com/kyverno/kyverno-json/releases/download/v0.0.3-beta.1/kyverno-json_darwin_arm64.tar.gz"
      sha256 "980067d6d901b1a3a57f126a02b17cead151d58eb289d0dae9016e1cd22be9c6"

      def install
        bin.install "kyverno-json"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyverno/kyverno-json/releases/download/v0.0.3-beta.1/kyverno-json_linux_amd64.tar.gz"
        sha256 "2b67d915ec90ce0bb37df1a8c631dd5ae03c789eedbfa5a57e9abde09f6132f9"

        def install
          bin.install "kyverno-json"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyverno/kyverno-json/releases/download/v0.0.3-beta.1/kyverno-json_linux_arm64.tar.gz"
        sha256 "6013ed62e7abab01d6a484fba94e3a512dd7ac06804ebdef00826c4a1513a046"

        def install
          bin.install "kyverno-json"
        end
      end
    end
  end
end
