apiVersion: tf.kyverno.io/v1alpha1
kind: Policy
metadata:
  name: required-s3-tags
spec:
  rules:
    - name: require-team-tag
      match:
        any:
        - resource:
            type: aws_s3_bucket
      # exclude:
      #   any:
      #   - resource:
      #       name: example
      validate:
        message: 'A team tag is required for all S3 buckets'
        pattern:
          values:
            tags:
              Team: ?*
