/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kyverno/kyverno-json/pkg/apis/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ValidationPolicyLister helps list ValidationPolicies.
// All objects returned here must be treated as read-only.
type ValidationPolicyLister interface {
	// List lists all ValidationPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ValidationPolicy, err error)
	// Get retrieves the ValidationPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ValidationPolicy, error)
	ValidationPolicyListerExpansion
}

// validationPolicyLister implements the ValidationPolicyLister interface.
type validationPolicyLister struct {
	indexer cache.Indexer
}

// NewValidationPolicyLister returns a new ValidationPolicyLister.
func NewValidationPolicyLister(indexer cache.Indexer) ValidationPolicyLister {
	return &validationPolicyLister{indexer: indexer}
}

// List lists all ValidationPolicies in the indexer.
func (s *validationPolicyLister) List(selector labels.Selector) (ret []*v1alpha1.ValidationPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ValidationPolicy))
	})
	return ret, err
}

// Get retrieves the ValidationPolicy from the index for a given name.
func (s *validationPolicyLister) Get(name string) (*v1alpha1.ValidationPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("validationpolicy"), name)
	}
	return obj.(*v1alpha1.ValidationPolicy), nil
}
